# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/FPGA/mqnic_prj/mqnic_prj.runs/synth_1/fpga.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu7ev-ffvc1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA/mqnic_prj/mqnic_prj.cache/wt [current_project]
set_property parent.project_path D:/FPGA/mqnic_prj/mqnic_prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/FPGA/mqnic_prj/mqnic_prj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property generic {FPGA_ID=32'h04730093 FW_ID=32'h00000000 FW_VER=32'h00000100 BOARD_ID=32'h10ee906a BOARD_VER=32'h01000000 BUILD_DATE=32'd1783950777 GIT_HASH=32'h00000000 RELEASE_INFO=32'h00000000 TDMA_BER_ENABLE=0 PORTS_PER_IF=1 SCHED_PER_IF=1 PORT_MASK=0 CLK_PERIOD_NS_NUM=4 CLK_PERIOD_NS_DENOM=1 PTP_CLOCK_PIPELINE=0 PTP_CLOCK_CDC_PIPELINE=0 PTP_PORT_CDC_PIPELINE=0 PTP_PEROUT_ENABLE=1 PTP_PEROUT_COUNT=1 EVENT_QUEUE_OP_TABLE_SIZE=32 TX_QUEUE_OP_TABLE_SIZE=32 RX_QUEUE_OP_TABLE_SIZE=32 CQ_OP_TABLE_SIZE=32 EQN_WIDTH=6 TX_QUEUE_INDEX_WIDTH=13 RX_QUEUE_INDEX_WIDTH=8 CQN_WIDTH=14 EQ_PIPELINE=3 TX_QUEUE_PIPELINE=4 RX_QUEUE_PIPELINE=3 CQ_PIPELINE=5 TX_DESC_TABLE_SIZE=32 RX_DESC_TABLE_SIZE=32 RX_INDIR_TBL_ADDR_WIDTH=8 TX_SCHEDULER_OP_TABLE_SIZE=32 TX_SCHEDULER_PIPELINE=4 TDMA_INDEX_WIDTH=6 PTP_TS_ENABLE=1 TX_CPL_FIFO_DEPTH=32 TX_CHECKSUM_ENABLE=1 RX_HASH_ENABLE=1 RX_CHECKSUM_ENABLE=1 PFC_ENABLE=1 LFC_ENABLE=1 ENABLE_PADDING=1 ENABLE_DIC=1 MIN_FRAME_LENGTH=64 TX_FIFO_DEPTH=32768 RX_FIFO_DEPTH=65536 MAX_TX_SIZE=9214 MAX_RX_SIZE=9214 TX_RAM_SIZE=32768 RX_RAM_SIZE=32768 DDR_CH=1 DDR_ENABLE=0 AXI_DDR_ID_WIDTH=8 AXI_DDR_MAX_BURST_LEN=256 APP_ID=32'h00000000 APP_ENABLE=0 APP_CTRL_ENABLE=1 APP_DMA_ENABLE=1 APP_AXIS_DIRECT_ENABLE=1 APP_AXIS_SYNC_ENABLE=1 APP_AXIS_IF_ENABLE=1 APP_STAT_ENABLE=1 DMA_IMM_ENABLE=0 DMA_IMM_WIDTH=32 DMA_LEN_WIDTH=16 DMA_TAG_WIDTH=16 RAM_ADDR_WIDTH=15 RAM_PIPELINE=2 IRQ_INDEX_WIDTH=6 AXIL_CTRL_DATA_WIDTH=32 AXIL_CTRL_ADDR_WIDTH=24 AXIL_APP_CTRL_DATA_WIDTH=32 AXIL_APP_CTRL_ADDR_WIDTH=24 AXIS_ETH_TX_PIPELINE=0 AXIS_ETH_TX_FIFO_PIPELINE=2 AXIS_ETH_TX_TS_PIPELINE=0 AXIS_ETH_RX_PIPELINE=0 AXIS_ETH_RX_FIFO_PIPELINE=2 STAT_ENABLE=1 STAT_DMA_ENABLE=1 STAT_PCIE_ENABLE=1 STAT_INC_WIDTH=24 STAT_ID_WIDTH=12 AXIS_PCIE_DATA_WIDTH=128 IF_COUNT=1} [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axi/rtl/arbiter.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axi/rtl/axil_crossbar.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axi/rtl/axil_crossbar_addr.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axi/rtl/axil_crossbar_rd.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axi/rtl/axil_crossbar_wr.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axi/rtl/axil_reg_if.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axi/rtl/axil_reg_if_rd.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axi/rtl/axil_reg_if_wr.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axi/rtl/axil_register_rd.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axi/rtl/axil_register_wr.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axis/rtl/axis_adapter.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axis/rtl/axis_arb_mux.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axis/rtl/axis_async_fifo.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axis/rtl/axis_async_fifo_adapter.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axis/rtl/axis_demux.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axis/rtl/axis_fifo.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axis/rtl/axis_fifo_adapter.v
  D:/FPGA/mqnic_prj/rtl/gmii_mac/axis_gmii_rx.v
  D:/FPGA/mqnic_prj/rtl/gmii_mac/axis_gmii_tx.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axis/rtl/axis_pipeline_fifo.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/cpl_op_mux.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/cpl_queue_manager.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/cpl_write.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/debounce_switch.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/desc_fetch.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/desc_op_mux.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/dma_client_axis_sink.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/dma_client_axis_source.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/dma_if_desc_mux.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/dma_if_mux.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/dma_if_mux_rd.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/dma_if_mux_wr.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/dma_if_pcie.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/dma_if_pcie_rd.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/dma_if_pcie_wr.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/dma_psdpram.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/dma_ram_demux_rd.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/dma_ram_demux_wr.v
  D:/FPGA/mqnic_prj/rtl/gmii_mac/eth_mac_1g.v
  D:/FPGA/mqnic_prj/rtl/gmii_mac/eth_mac_1g_fifo.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/fpga_core.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/irq_rate_limit.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/eth/rtl/lfsr.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/eth/rtl/mac_ctrl_rx.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/eth/rtl/mac_ctrl_tx.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/eth/rtl/mac_pause_ctrl_rx.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/eth/rtl/mac_pause_ctrl_tx.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_core.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_core_pcie.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_core_pcie_us.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_dram_if.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_egress.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_ingress.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_interface.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_interface_rx.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_interface_tx.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_l2_egress.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_l2_ingress.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_port.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_port_rx.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_port_tx.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_ptp.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_ptp_clock.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_ptp_perout.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_rb_clk_info.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_rx_queue_map.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/mqnic_tx_scheduler_block_rr.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/pcie_axil_master.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/pcie_msix.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/pcie_tlp_demux.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/pcie_tlp_demux_bar.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/pcie_tlp_fifo.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/pcie_tlp_fifo_raw.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/pcie_tlp_mux.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/pcie_us_cfg.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/pcie_us_if.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/pcie_us_if_cc.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/pcie_us_if_cq.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/pcie_us_if_rc.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/pcie_us_if_rq.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axi/rtl/priority_encoder.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/eth/rtl/ptp_perout.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/eth/rtl/ptp_td_leaf.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/eth/rtl/ptp_td_phc.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/pcie/rtl/pulse_merge.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/queue_manager.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/rx_checksum.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/rx_engine.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/rx_fifo.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/rx_hash.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/stats_collect.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/stats_counter.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/stats_dma_if_pcie.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/stats_dma_latency.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/stats_pcie_if.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/stats_pcie_tlp.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/lib/axis/rtl/sync_reset.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/sync_signal.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/tx_checksum.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/tx_engine.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/tx_fifo.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/tx_req_mux.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/common/tx_scheduler_rr.v
  D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/imports/fpga_pcie/rtl/fpga.v
}
read_ip -quiet D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/gig_ethernet_pcs_pma_0/ip_0/synth/gig_ethernet_pcs_pma_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/gig_ethernet_pcs_pma_0/ip_0/synth/gig_ethernet_pcs_pma_0_gt.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0_ooc.xdc]

read_ip -quiet D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/ip/pcie4_uscale_plus_0/pcie4_uscale_plus_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/pcie4_uscale_plus_0/pcie4_uscale_plus_0_board.xdc]
set_property used_in_synthesis false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/pcie4_uscale_plus_0/source/ip_pcie4_uscale_plus_impl_x0y0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/pcie4_uscale_plus_0/source/ip_pcie4_uscale_plus_impl_x0y0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_late.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/pcie4_uscale_plus_0/source/ip_pcie4_uscale_plus_x0y0.xdc]

read_ip -quiet D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet D:/FPGA/mqnic_prj/mqnic_prj.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/mqnic_prj/mqnic_prj.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/mqnic/ZCU106/fpga_pcie/fpga.xdc
set_property used_in_implementation false [get_files D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/mqnic/ZCU106/fpga_pcie/fpga.xdc]

read_xdc -unmanaged D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/mqnic/ZCU106/fpga_pcie/lib/axis/syn/vivado/axis_async_fifo.tcl
set_property used_in_implementation false [get_files D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/mqnic/ZCU106/fpga_pcie/lib/axis/syn/vivado/axis_async_fifo.tcl]

read_xdc -unmanaged D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/mqnic/ZCU106/fpga_pcie/lib/axis/syn/vivado/sync_reset.tcl
set_property used_in_implementation false [get_files D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/mqnic/ZCU106/fpga_pcie/lib/axis/syn/vivado/sync_reset.tcl]

read_xdc -unmanaged D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/mqnic/ZCU106/fpga_pcie/lib/eth/syn/vivado/ptp_td_leaf.tcl
set_property used_in_implementation false [get_files D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/mqnic/ZCU106/fpga_pcie/lib/eth/syn/vivado/ptp_td_leaf.tcl]

read_xdc -unmanaged D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/common/syn/vivado/mqnic_port.tcl
set_property used_in_implementation false [get_files D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/common/syn/vivado/mqnic_port.tcl]

read_xdc -unmanaged D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/common/syn/vivado/mqnic_ptp_clock.tcl
set_property used_in_implementation false [get_files D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/common/syn/vivado/mqnic_ptp_clock.tcl]

read_xdc -unmanaged D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/common/syn/vivado/mqnic_rb_clk_info.tcl
set_property used_in_implementation false [get_files D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/common/syn/vivado/mqnic_rb_clk_info.tcl]

read_xdc -unmanaged D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/common/syn/vivado/rb_drp.tcl
set_property used_in_implementation false [get_files D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/common/syn/vivado/rb_drp.tcl]

read_xdc -unmanaged D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/common/syn/vivado/eth_xcvr_phy_10g_gty_wrapper.tcl
set_property used_in_implementation false [get_files D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/common/syn/vivado/eth_xcvr_phy_10g_gty_wrapper.tcl]

read_xdc -unmanaged D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/common/syn/vivado/tdma_ber_ch.tcl
set_property used_in_implementation false [get_files D:/FPGA/mqnic_prj/mqnic_prj.srcs/constrs_1/imports/fpga/common/syn/vivado/tdma_ber_ch.tcl]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top fpga -part xczu7ev-ffvc1156-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fpga_utilization_synth.rpt -pb fpga_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
